@baseUrl = http://localhost:4004/odata/v4/main
@id = 0e21abb6-0a7e-4899-8412-bd204194e232


### GET – listar clientes
GET {{baseUrl}}/Customers
Content-Type: application/json


### POST – criar cliente
POST {{baseUrl}}/Customers
Content-Type: application/json

{
  "id": "{{id}}",
  "firstName": "Jean",
  "lastName": "Souza",
  "email": "jean.cardosodesouza@gmail.com"
}


### DELETE – remover cliente
DELETE {{baseUrl}}/Customers('{{id}}')
Content-Type: application/json


### PUT – atualizar todos exceto as chaves colocando o resto como nulo
PUT  {{baseUrl}}/Customers('{{id}}')
Content-Type: application/json

{
  "firstName": "Teste"
}


### PATCH – atualizar parcialmente (recomendado)
PATCH {{baseUrl}}/Customers('{{id}}')
Content-Type: application/json

{
  "firstName": "Teste"
}

