@baseUrl = http://localhost:4004/odata/v4/main
@id = abc2e239-0ddd-4674-b3cf-9a9c2accca1c


### GET – listar clientes
GET {{baseUrl}}/Customers
Content-Type: application/json


### POST – criar cliente
POST {{baseUrl}}/Customers
Content-Type: application/json

{
  "id": "{{id}}",
  "firstName": "Jean",
  "lastName": "Cardoso",
  "email": "jean.cardosodesouza@gmail.com"
}



### DELETE – remover cliente
DELETE  {{baseUrl}}/Customers(id={{id}})
Content-Type: application/json



### PUT – atualizar todos exceto as chaves colocando o resto como nulo
PUT  {{baseUrl}}/Customers(id={{id}})
Content-Type: application/json

{
  "firstName": "Jean",
  "lastName": "Cardoso de Souza"
}


### PATCH – atualizar parcialmente (recomendado)
PATCH {{baseUrl}}/Customers('{{id}}')
Content-Type: application/json

{
  "firstName": "Jean"
  "lastName": "Cardoso Souza",
}

