@localhost=localhost:4004/odata/v4/main

GET http://{{localhost}}/Customers
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

{
    "id": "3134bfd8-0683-4393-bd3f-ac24ae652d00",
    "firstName": "Jean",
    "lastName": "Souza",
    "email": "jean.cardosodesouza@gmail.com"
}

# entity Customers : managed {
#   key id: UUID;
#   firstName : String(20);
#   lastName  : String(100);
#   email     : String(255);