@baseUrl = http://localhost:4004/odata/v4/main
@id = 37240989-abd8-4cbc-a3f3-deecfb02c4f8
@customerId = 31426727-3bf7-48b7-972f-c9c5d3a6f5eb
@productId1 = 29801137-ad77-4ba8-b161-2c43d2e204ae
#6358761f-1aeb-44c0-976c-6bff6cafb12d
@productId2 = 29801137-ad77-4ba8-b161-2c43d2e204ae



############################################
# GET – Seleciona pedido (CAP IDs)
############################################
GET {{baseUrl}}/SalesOrderHeaders?filter=id eq "{{id}}"&$expand=items
Content-Type: application/json


###
############################################
# POST – Criar novo pedido (CAP gera IDs)
############################################
POST {{baseUrl}}/SalesOrderHeaders
Content-Type: application/json

{
  "id": "{{id}}",
   "customer_id": "{{customerId}}",
  "totalAmount": 398,
  "items": [
    {
      "product_id": "{{productId1}}",
      "quantity": 10,
      "price": 2.99
    },
    {
      "id": "{{id}}",
      "product_id": "{{productId2}}",
      "quantity": 5,
      "price": 2.98
    }
  ]
}


###
############################################
# POST – Validação do itens - srv/maim.ts

        #if (!params.items || params.items.length === 0) {
            #return request.reject(400, 'Itens inválidos');
        #}

POST {{baseUrl}}/SalesOrderHeaders
Content-Type: application/json

{
  "id": "{{id}}",
   "customer_id": "{{customerId}}",
  "totalAmount": 398
}
############################################


###
############################################
# DELETE – Deletar pedido
############################################
DELETE  {{baseUrl}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json





###
############################################
# PATCH – Atualizar valor total do pedido
############################################
PATCH {{baseUrl}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

{
  "totalAmount": 99.99,
  "items": [
    {
      "product_id": "{{productId}}",
      "quantity": 100,
      "price": 1.99
    }
  ]
}



###
############################################
# GET – Testando filtros
#http://localhost:4004/odata/v4/main/SalesOrderHeaders?$filter=totalAmount%20ge%203768.44
#http://localhost:4004/odata/v4/main/SalesOrderHeaders?$filter=totalAmount%20le%203768.44
############################################
GET {{baseUrl}}/SalesOrderHeaders?filter=id eq {{id}}&$expand=items
Content-Type: application/json

###
GET {{baseUrl}}/SalesOrderHeaders?$filter=totalAmount ge 3768.44
Content-Type: application/json

###
GET {{baseUrl}}/SalesOrderHeaders?$filter=totalAmount le 3768.44
Content-Type: application/json


###
GET {{baseUrl}}/SalesOrderHeaders?filter=id eq "{{id}}"&$expand=items
Content-Type: application/json

###
GET {{baseUrl}}/SalesOrderHeaders?$filter=totalAmount gt 57597.48
Content-Type: application/json

###
############################################
# GET – Expandindo Itens
#http://localhost:4004/odata/v4/main/SalesOrderHeaders?$filter=totalAmount%20ge%203768.44
#http://localhost:4004/odata/v4/main/SalesOrderHeaders?$filter=totalAmount%20le%203768.44

GET {{baseUrl}}/SalesOrderHeaders?$filter=totalAmount gt 57597.48&$expand=items($expand=product),customer
Content-Type: application/json

###

GET {{baseUrl}}/SalesOrderHeaders?$expand=items($expand=product;$filter=quantity le 58),customer
Content-Type: application/json

############################################

###
############################################
# GET – Select - Selecionar customer e id so sales orger hearders
GET {{baseUrl}}/SalesOrderHeaders?$select=id,customer&$expand=customer($select=id,email)
Content-Type: application/json
############################################

###
############################################
# GET – Descobrindo a quantidade de registro


GET {{baseUrl}}/SalesOrderHeaders/$count
Content-Type: application/json

###

#Paginadno os registros
GET {{baseUrl}}/SalesOrderHeaders?$skip=5
Content-Type: application/json


###

#Paginadno os registros com skip e top
GET {{baseUrl}}/SalesOrderHeaders?$skip=1&$top=5
Content-Type: application/json

############################################

###
############################################
# Search – Buscar
############################################
GET {{baseUrl}}/SalesOrderHeaders?$search=bnvzp&$filter=totalAmount gt 57597.47

###
############################################
# POST – Criar novo pedido (CAP gera IDs)
############################################
POST {{baseUrl}}/SalesOrderHeaders