@baseUrl = http://localhost:4004/odata/v4/main
@id=7240989-abd8-4cbc-a3f3-deecfb02c4f8'
@customerId = abc2e239-0ddd-4674-b3cf-9a9c2accca1c
@productId = 29801137-ad77-4ba8-b161-2c43d2e204ae




GET {{baseUrl}}/SalesOrderHeaders?filter=id eq "{{id}}"&$expand=items
Content-Type: application/json

###

############################################
# POST – Criar novo pedido (CAP gera IDs)
############################################

POST {{baseUrl}}/SalesOrderHeaders
Content-Type: application/json

{
  "id": "{{id}}",
  "customer_id": "{{customerId}}",
  "totalAmount": 398,
  "items": [
    {
      "product_id": "{{productId}}",
      "quantity": 10,
      "price": 2.99
    },
    {
      "id": "{{id}}",
      "product_id": "{{productId}}",
      "quantity": 10,
      "price": 2.98
    }
  ]
}

###

DELETE  {{baseUrl}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json


###

############################################
# PATCH – Atualizar valor total do pedido
############################################


PATCH {{baseUrl}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

{
  "totalAmount": 250.00
}


###